### ISSUE TITLE
archlinux can't login

### ISSUE THREAD

**Issue by itswcg** [klaussinani/tusk#173]
manjaro can't click the button of continue of google and can't login.
### error 
(process:8943): GLib-CRITICAL **: 10:39:40.012: g_file_test: assertion 'filename != NULL' failed
sh: gtk-update-icon-cache-3.0: command not found
gtk-update-icon-cache: Cache file created successfully.
Gtk-Message: 10:39:43.176: Failed to load module "appmenu-gtk-module"
{ Error: Cannot find module '../screen'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/tmp/.mount_tusk-0FNaDff/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.get [as screen] (/tmp/.mount_tusk-0FNaDff/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at Win.get _screenDimensions [as _screenDimensions] (/tmp/.mount_tusk-0FNaDff/resources/app.asar/src/win.js:12:38)
    at Win.get _minDimensions [as _minDimensions] (/tmp/.mount_tusk-0FNaDff/resources/app.asar/src/win.js:33:40)
    at Win.get defaultOpts [as defaultOpts] (/tmp/.mount_tusk-0FNaDff/resources/app.asar/src/win.js:38:35)
    at createMainWindow (/tmp/.mount_tusk-0FNaDff/resources/app.asar/index.js:42:44) code: 'MODULE_NOT_FOUND' }

**Comment by ivnilv** [comment]
same issue with ubuntu 19.10 running on Wayland ...
